# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  encoding: utf8
  database: blockbuster_dev
  pool: 5
  username: 'ericolszewski'
  password: 'root'

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: blockbuster_test
  pool: 5
  username: 'ericolszewski'
  password: 'root'

production:
  adapter: postgresql
  encoding: utf8
  database: blockbuster_prod
  pool: 5
  username: 'ericolszewski'
  password: 'root'